### ISSUE TITLE
Cannot load rails server.

### ISSUE THREAD

**Issue by kingscott** [Shopify/pos-app-sdk-example#2]
I've started working on a POS app leveraging the Shopify POS SDK. I've been getting familiar with the SDK methods and want to mess around with this example app. 

Unfortunately, I'm unable to get the app running. I have my credentials defined in `config/initializers/shopify_app.rb`:

```ruby
ShopifyApp.configure do |config|
  config.api_key = "{my_key}"
  config.secret = "{my_secret}"
  config.redirect_uri = "http://1234abcd.ngrok.io/auth/shopify/callback"
  config.scope = "read_orders, read_products"
  config.embedded_app = true
end
```

My ngrok config is all set and ready to go, but upon running `bundle exec rails server` I get these errors:

```bash
➜  pos-app-sdk-example git:(master) ✗ bundle exec rails server
=> Booting WEBrick
=> Rails 4.2.5.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/kingscott/pos-app-sdk-example/config/initializers/shopify_app.rb:4:in `block in <top (required)>': undefined method `redirect_uri=' for #<ShopifyApp::Configuration:0x007fa937c39078> (NoMethodError)
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/shopify_app-7.0.2/lib/shopify_app/configuration.rb:40:in `configure'
	from /Users/kingscott/pos-app-sdk-example/config/initializers/shopify_app.rb:1:in `<top (required)>'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:651:in `load_config_initializer'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `each'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `each'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/kingscott/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/kingscott/pos-app-sdk-example/config/environment.rb:5:in `<top (required)>'
	from /Users/kingscott/pos-app-sdk-example/config.ru:3:in `require'
	from /Users/kingscott/pos-app-sdk-example/config.ru:3:in `block in <main>'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/kingscott/pos-app-sdk-example/config.ru:in `new'
	from /Users/kingscott/pos-app-sdk-example/config.ru:in `<main>'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands/server.rb:61:in `app'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands/server.rb:78:in `start'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/kingscott/pos-app-sdk-example/bin/rails:9:in `require'
	from /Users/kingscott/pos-app-sdk-example/bin/rails:9:in `<top (required)>'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
	from /Users/kingscott/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/kingscott/pos-app-sdk-example/bin/spring:13:in `require'
	from /Users/kingscott/pos-app-sdk-example/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Unfortunately, I'm sure what the exact issue is, I'm only assuming it is something to do with the `redirect_uri`. The docs don't really go into any detail besides explaining the basics of getting the app up and running. Any help is appreciated, thanks.

**Comment by kingscott** [comment]
Fixed by [this](https://github.com/Shopify/pos-app-sdk-example/pull/1).
