### ISSUE TITLE
Newer Ruby Version Compatibility?

### ISSUE THREAD

**Issue by gregarican** [Shopify/pos-app-sdk-example#9]
Have a clean Ubuntu 18.04.2 install, and added Ruby 2.5.1, along with the proper development libraries and requirements for Rails to run. This example won't install as a bundle. Assuming due to breaking changes in how Ruby moved FixNum and BigNum objects into a new Integer object.  

Any plans to update this example to Ruby >= 2.4.0?

**Comment by gregarican** [comment]
You can close the issue. It's a deeper issue than that. Rails itself had references to these objects and that's why the server wouldn't launch for this example.

**Comment by Messhias** [comment]
@gregarican I opened a pull request to merge with my docker container version with latest ruby version check #10

**Comment by Messhias** [comment]
@jahfer can you please review the PR #10 and merge it to close this issue?

Thank you,

**Comment by gregarican** [comment]
So once this pull has been merged then I assume the download will successfully install if I give it a shot again?

**Comment by Messhias** [comment]
> So once this pull has been merged then I assume the download will successfully install if I give it a shot again?

@gregarican  sorry, but I didn't understood what you asked.

Can you please explain exactly what do you mean?

Thank you,

**Comment by gregarican** [comment]
If you look at my first post in this thread you will see what I'm asking. If I can download and install this particular GitHub project on a clean Ubuntu 18.04.2 install that has Ruby 2.5.1 on it.

**Comment by Messhias** [comment]
@gregarican I'm not talking about that, I create PR to you can work inside the dockers containers, but anyway, if you want to install on your local ubuntu or whatever operating system you want to use just follow the Dockerfile config adapted to your OS commands.

**Comment by gregarican** [comment]
Okay, I applied those changed files you had committed and ran docker-compose up --build. At first I received an unsupported version error from the docker-compose.yml file. I tried changing the version referenced in the yml file to 3.7. Since I had assumedly already installed the latest versions of docker and docker-compose (18.09.7 and 1.17.1, respectively). The error persisted, so I read somewhere about changing the version to 2 in the yml file. Then the build routine ran fine. Up until the last step. I'll paste a snippet of the error specifics below.

`Step 12/13 : EXPOSE 3000
 ---> Running in 542463c93f6e
Removing intermediate container 542463c93f6e
 ---> 3cb264f9bdc7
Step 13/13 : CMD ["rails", "server", "-b", "0.0.0.0"]
 ---> Running in 8a0afe13a2ca
Removing intermediate container 8a0afe13a2ca
 ---> da1f60ddd535
Successfully built da1f60ddd535
Successfully tagged posappsdkexamplemaster_web:latest
Recreating posappsdkexamplemaster_web_1 ...
Recreating posappsdkexamplemaster_web_1 ... done
Attaching to posappsdkexamplemaster_web_1
web_1  | rake aborted!
web_1  | NameError: uninitialized constant ShopifyApp::Shop
web_1  | /app/app/models/shop.rb:2:in `<class:Shop>'
web_1  | /app/app/models/shop.rb:1:in `<top (required)>'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
web_1  | /app/config/initializers/shopify_session_repository.rb:5:in `block in <top (required)>'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:396:in `instance_exec'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:396:in `block in make_lambda'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:546:in `catch'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:546:in `block in default_terminator'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:170:in `block in halting'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:454:in `block in call'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:454:in `each'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:454:in `call'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_prepare_callbacks'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
web_1  | /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/reloader.rb:87:in `prepare!'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `instance_exec'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `run'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/initializable.rb:55:in `block in run_initializers'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/initializable.rb:54:in `run_initializers'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/application.rb:352:in `initialize!'
web_1  | /app/config/environment.rb:5:in `<top (required)>'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/application.rb:328:in `require_environment!'
web_1  | /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
web_1  | /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
web_1  | /usr/local/bin/bundle:30:in `block in <main>'
web_1  | /usr/local/bin/bundle:22:in `<main>'
web_1  | Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
web_1  | (See full trace by running task with --trace)
web_1  | Created database 'db/development.sqlite3'
web_1  | Created database 'db/test.sqlite3'
posappsdkexamplemaster_web_1 exited with code 1
root@RubyOnRails-VM:/home/vm-admin/pos-app-sdk-example-master#`

**Comment by gregarican** [comment]
I see now I had to comment out a line in the shopify_api's shop.rb file. As described in https://github.com/Shopify/shopify_app/blob/master/CHANGELOG.md#800. Now I am able to get the Rails app loaded successfully.

**Comment by Messhias** [comment]
@gregarican now it's fine? If you can, try to improve it, unfortunately, some stuff on this API doesn't make sense (like comment shopify_api line in shop.rb).

But since we aren't using Shopify anymore here I leave behind and create the PR to help you and the others.

To be honest this repository is abandonned.
